name: mushroom-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - pip:
      - mlflow==2.13.2
      - dagshub>=0.3.0
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - urllib3<2.0
