name: mushroom-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - pip:
      - mlflow>=2.9.0
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
