name: mushroom-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.13.2
      - pandas
      - scikit-learn
      - dagshub
      - matplotlib
      - seaborn
