name: Model CI - THE BENAR2 FIX VERSION

on:
  push:
    branches:
      - main
    paths:
      - "MLProject_folder/**"
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: MLProject_folder/conda.yaml
          activate-environment: mushroom-env

      - name: 3. Run Training Directly
        id: training_step
        shell: bash -l {0}
        run: |
          set -e
          cd MLProject_folder
          python modelling.py | tee ../modelling_log.txt
          cd ..
          RUN_ID=$(grep 'MLflow Run ID:' modelling_log.txt | awk '{print $4}')
          if [ -z "$RUN_ID" ]; then
            echo "::error::Could not find MLflow Run ID."
            exit 1
          fi
          echo "Run ID captured: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: 4. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 5. Build and Push Docker Image
        env:
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject_folder/mlruns"
        shell: bash -l {0}
        run: |
          set -e
          MODEL_URI="runs:/${{ steps.training_step.outputs.run_id }}/model"
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mushroom-classifier-msml:${{ github.sha }}"

          echo "INFO: Building Docker image from local URI: $MODEL_URI"
          echo "INFO: Using Tracking URI: $MLFLOW_TRACKING_URI"

          # Solusi pamungkas: Gunakan environment manager lokal
          mlflow models build-docker --model-uri "$MODEL_URI" --name "$IMAGE_NAME" --env-manager local

          echo "INFO: Pushing image to Docker Hub..."
          docker push "$IMAGE_NAME"
          echo "✅ Docker image ${IMAGE_NAME} pushed successfully."
