name: Model CI - Training and Docker Push

on:
  push:
    branches:
      - main
    paths:
      - "MLProject_folder/**"
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLProject_folder

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 3. Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: 3.5 Debug Environment Variables
        run: |
          echo "DEBUG: DagsHub Owner is ${{ secrets.DAGSHUB_OWNER }}"
          echo "DEBUG: DagsHub Repo Name is ${{ secrets.DAGSHUB_REPO_NAME }}"
          if [ -n "${{ secrets.DAGSHUB_TOKEN }}" ]; then
            echo "DEBUG: DagsHub Token is SET."
          else
            echo "DEBUG: DagsHub Token is NOT SET or EMPTY!"
          fi

      - name: 4. Create Conda Env & Run Training
        env:
          DAGSHUB_OWNER: ${{ secrets.DAGSHUB_OWNER }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          echo "INFO: Membuat environment conda dari file .yaml..."
          conda env create -f conda.yaml --name mushroom-env

          echo "INFO: Mengaktifkan environment..."
          conda activate mushroom-env

          echo "INFO: Menjalankan script training Python..."
          python modelling.py

          echo "INFO: Training selesai."

      - name: 5. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. Build and Push Docker Image (Advanced)
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/${{ secrets.DAGSHUB_OWNER }}/${{ secrets.DAGSHUB_REPO_NAME }}.mlflow"
        shell: bash -l {0}
        run: |
          echo "INFO: Mengaktifkan environment conda..."
          conda activate mushroom-env

          echo "INFO: Membangun image Docker dari model..."
          MODEL_NAME="MushroomClassifierRF"
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mushroom-classifier-msml:${{ github.sha }}"

          mlflow models build-docker --model-uri "models:/${MODEL_NAME}/latest" --name "${IMAGE_NAME}" --enable-mlserver
          docker push "${IMAGE_NAME}"
          echo "Docker image ${IMAGE_NAME} berhasil di-push ke Docker Hub."
