name: Model CI - Train, Artifact, and Docker Push

on:
  push:
    branches:
      - main
    paths:
      - "MLProject_folder/**"
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: MLProject_folder/conda.yaml
          activate-environment: mushroom-env

      - name: 3. Run Training with Enhanced Debugging
        id: training_step
        # KOSONGKAN BAGIAN env INI KARENA TIDAK MENGHUBUNGI DAGSHUB
        # env:
        #   DAGSHUB_OWNER: ${{ secrets.DAGSHUB_OWNER }}
        shell: bash -l {0}
        run: |
          set -e

          echo "--- Menampilkan Struktur File dan Folder ---"
          ls -R
          echo "-------------------------------------------"

          echo "INFO: Pindah ke direktori kerja..."
          cd MLProject_folder

          echo "INFO: Menjalankan training via mlflow run (LOCAL TEST)..."
          mlflow run . | tee ../modelling_log.txt

          echo "INFO: Training complete."
          cd ..

          RUN_ID=$(grep 'MLflow Run ID:' modelling_log.txt | awk '{print $4}')
          if [ -z "$RUN_ID" ]; then
            echo "::error::Tidak bisa menemukan MLflow Run ID di log."
            exit 1
          fi

          echo "Berhasil mendapatkan MLflow Run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: 4. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 5. Build and Push Docker Image
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/${{ secrets.DAGSHUB_OWNER }}/${{ secrets.DAGSHUB_REPO_NAME }}.mlflow"
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          set -e
          MODEL_URI="runs:/${{ steps.training_step.outputs.run_id }}/model"
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mushroom-classifier-msml:${{ github.sha }}"

          echo "INFO: Membangun Docker image dari URI: $MODEL_URI"
          mlflow models build-docker --model-uri "$MODEL_URI" --name "$IMAGE_NAME"

          echo "INFO: Mendorong image ke Docker Hub..."
          docker push "$IMAGE_NAME"
          echo "✅ Docker image ${IMAGE_NAME} berhasil didorong."
