name: Model CI - YUK BISAAA

on:
  push:
    branches:
      - main
    paths:
      - "MLProject_folder/**"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: MLProject_folder/conda.yaml
          activate-environment: mushroom-env
          
      - name: 3. Run mlflow project
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mushroom-env
          mlflow run ./MLProject_folder
          
      - name: 4. Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      - name: 5. Archive model artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow_model
          path: mlruns/
          
      - name: 6. Set SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        
      - name: 7. Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ml_model_${{ env.SHORT_SHA }}
          name: 'Model Release'
          files: mlruns/**
          
      - name: 8. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 9. Build and Push Docker Image
        env:
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject_folder/mlruns"
        shell: bash -l {0}
        run: |
          set -e
          MODEL_URI="runs:/${{ steps.training_step.outputs.run_id }}/model"
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mushroom-classifier-msml:${{ github.sha }}"

          echo "INFO: Building Docker image from local URI: $MODEL_URI"
          echo "INFO: Using Tracking URI: $MLFLOW_TRACKING_URI"

          mlflow models build-docker --model-uri "$MODEL_URI" --name "$IMAGE_NAME"

          echo "INFO: Pushing image to Docker Hub..."
          docker push "$IMAGE_NAME"
          echo "✅ Docker image ${IMAGE_NAME} pushed successfully."
