name: Final CI - Training, Artifact, Docker

on:
  push:
    branches:
      - main
    paths:
      - "MLProject_folder/**"
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: 3. Run Training and Get Run ID
        id: training_step # Memberi ID pada langkah ini
        env:
          DAGSHUB_OWNER: ${{ secrets.DAGSHUB_OWNER }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          echo "INFO: Membuat environment conda..."
          conda env create -f MLProject_folder/conda.yaml --name mushroom-env
          conda activate mushroom-env
          echo "INFO: Menjalankan script training..."
          # Menjalankan script dan menyimpan outputnya ke file log
          python MLProject_folder/modelling.py > modelling_log.txt
          echo "INFO: Training selesai."

          # Mengambil Run ID dari log dan menyetelnya sebagai output
          RUN_ID=$(grep 'MLflow Run ID:' modelling_log.txt | awk '{print $4}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      - name: 4. Download Artifacts from DagsHub
        # download artefak dari DagsHub untuk disimpan ke GitHub
        run: |
          pip install mlflow==2.19.0 dagshub
          dagshub.init(repo_owner='${{ secrets.DAGSHUB_OWNER }}', repo_name='${{ secrets.DAGSHUB_REPO_NAME }}', mlflow=True)
          mlflow.artifacts.download_artifacts(run_id='${{ steps.training_step.outputs.RUN_ID }}', dst_path='./mlflow_artifacts')
        shell: python {0}

      - name: 5. Save MLflow artifacts to GitHub (Skilled Requirement)
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts
          path: ./mlflow_artifacts/

      - name: 6. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 7. Build and Push Docker Image (Advanced Requirement)
        run: |
          pip install mlflow==2.19.0

          MODEL_URI="runs:/${{ steps.training_step.outputs.RUN_ID }}/model"
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mushroom-classifier-msml:${{ github.sha }}"

          echo "INFO: Membangun Docker image dari URI: $MODEL_URI"
          mlflow models build-docker --model-uri "$MODEL_URI" --name "$IMAGE_NAME" --enable-mlserver

          echo "INFO: Mendorong image ke Docker Hub..."
          docker push "$IMAGE_NAME"
          echo "Docker image ${IMAGE_NAME} berhasil di-push."
