name: Model CI - Train, Artifact, and Docker Push

on:
  push:
    branches:
      - main
    paths:
      - "MLProject_folder/**"
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: MLProject_folder/conda.yaml
          activate-environment: mushroom-env

      - name: 3. Run Training with MLflow Project
        id: training_step
        env:
          DAGSHUB_OWNER: ${{ secrets.DAGSHUB_OWNER }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          set -e # Hentikan skrip jika ada perintah yang gagal

          echo "INFO: Running training via mlflow run..."
          cd MLProject_folder

          mlflow run . | tee ../modelling_log.txt

          echo "INFO: Training complete."
          cd ..

          # Validasi dan ekstrak Run ID dengan lebih aman
          RUN_ID=$(grep 'MLflow Run ID:' modelling_log.txt | awk '{print $4}')
          if [ -z "$RUN_ID" ]; then
            echo "::error::Could not find MLflow Run ID in the log. The training script might have failed."
            echo "--- Log Content ---"
            cat modelling_log.txt
            echo "--- End Log Content ---"
            exit 1
          fi

          echo "Extracted MLflow Run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: 4. Upload Training Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: training-log
          path: modelling_log.txt

      - name: 5. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. Build and Push Docker Image
        env:
          # Set variabel environment agar mlflow tahu di mana harus mencari run
          MLFLOW_TRACKING_URI: "https://dagshub.com/${{ secrets.DAGSHUB_OWNER }}/${{ secrets.DAGSHUB_REPO_NAME }}.mlflow"
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          set -e
          MODEL_URI="runs:/${{ steps.training_step.outputs.run_id }}/model"
          # Gunakan commit SHA untuk tag yang unik
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mushroom-classifier-msml:${{ github.sha }}"

          echo "INFO: Building Docker image from URI: $MODEL_URI"
          mlflow models build-docker --model-uri "$MODEL_URI" --name "$IMAGE_NAME"

          echo "INFO: Pushing image to Docker Hub..."
          docker push "$IMAGE_NAME"
          echo "✅ Docker image ${IMAGE_NAME} pushed successfully."
